@echo off
echo Clearing Next.js build cache...
if exist .next rmdir /s /q .next
echo Clearing node_modules...
if exist node_modules rmdir /s /q node_modules
echo Reinstalling dependencies...
call npm install
echo Starting dev server...
call npm run dev

